### PR TITLE
remove bundled hmac-sha1.el

### PR DESCRIPTION
**Pull request by tarsius**
(Assuming depending on flim is okay with you)

### CODE REVIEW

**Comment by tarsius** [comment]
Just a friendly reminder.

**Comment by tarsius** [comment]
Ping.

**Comment by tarsius** [comment]
On #4  you said "Pull requests are welcome." Could you please merge.

**Comment by hellekin** [comment]
:+1:  This [howto for Pump.io support in Emacs](http://www.emacswiki.org/emacs/PumpioEl) seconds @tarsius, as indicated in [this commit](https://github.com/cnngimenez/pumpio-el/commit/bae30009a60b9efe27f63a43f8139c4c8afc4302), and #4 and #5.

@psanford are you on vacation? :)

**Comment by tarsius** [comment]
Pong.

**Comment by tarsius** [comment]
Could you please merge or reject this?

**Comment by psanford** [comment]
I don't want to break any existing users that are depending on this file.

**Comment by tarsius** [comment]
Okay. Thanks for the reply.

**Pull request closed without merging**
